import Head from 'next/head'

// components
import CTA from '../components/CTA'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div className='px-5'>
      <Head>
        <title>Web3</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='../public/assests/images/favicon-32x32.png' />
      </Head>
      <Navbar />
      <main className=''>
        <CTA />
      </main>
    </div>
  )
}
