import Head from 'next/head'
import { useState } from 'react'

// components
import CTA from '../components/CTA'
import Navbar from '../components/Navbar'
import NewSection from '../components/NewSection'

export default function Home() {
  const [isActive, setIsActive] = useState(false)

  const handleToggleNav = () => {
    setIsActive(!isActive)
    if (!isActive) {
      document.body.style.overflow = 'hidden'
    } else {
      document.body.style.overflow = 'auto'
    }
  }

  return (
    <div className='px-5'>
      <Head>
        <title>Web3</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='../public/assests/images/favicon-32x32.png' />
      </Head>
      <Navbar handleToggleNav={handleToggleNav} isActive={isActive} />
      <main>
        <CTA />
        <NewSection />
      </main>
    </div>
  )
}
